default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: test-task-db
  timeout: 5000
  username: postgres
  password:

development:
  <<: *default
  database: test_task_dev
